name: skGull
version: 0.0.3
main: org.serratedgull.skGull.SkGull
author: SerratedGull
description: Advanced Skript addon for entity interaction, raycasting, and more
api-version: 1.21
depend: [Skript]
softdepend: []
website: https://github.com/SerratedGull/skGull